version: '3.8'

services:
  x-scraper:
    build: .
    container_name: x-scraper
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Additional environment variables
    environment:
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    
    # Volume mounts for persistence
    volumes:
      - ./data:/app/data  # Session files, tweets, etc.
      - ./logs:/app/logs  # Log files
      - ./debug_logs:/app/debug_logs  # Debug logs for rate limiting
    
    # Network configuration for database access
    networks:
      - newsio-network
    
    # Default monitoring command
    command: >
      python scraper.py
      --url "https://x.com/i/lists/1919380958723158457"
      --interval 4
      --scrolls 3
      --limit 10

  # Proxy rotation test service
  proxy-test:
    build: .
    container_name: x-scraper-proxy-test
    env_file:
      - .env
    command: python tests/test_decodo_proxy.py
    networks:
      - newsio-network
    profiles:
      - testing

  # Database monitoring service
  db-monitor:
    build: .
    container_name: x-scraper-db-monitor
    restart: unless-stopped
    env_file:
      - .env
    command: python check_connections.py
    networks:
      - newsio-network
    profiles:
      - monitoring

  # Test runner service
  test-runner:
    build: .
    container_name: x-scraper-tests
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./debug_logs:/app/debug_logs
    command: python tests/test_runner.py
    networks:
      - newsio-network
    profiles:
      - testing

networks:
  newsio-network:
    external: true
    name: newsio-single_newsio-network